version: '3'

services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 8888:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        image: php:7-fpm
        volumes:
            - ./:/var/www
        ports:
            - 9999:9999
        
